project_id = "kugocdtesaczbfrwblsi"

[functions.create-application]
verify_jwt = false

[functions.openai-assistant]
verify_jwt = false
timeout_seconds = 120

[functions.extract-pdf-text]
verify_jwt = false
timeout_seconds = 180

# Environment variables for OpenAI
[env]
OPENAI_API_KEY = "your-openai-api-key"
MAX_FILE_SIZE_MB = "10"
ALLOWED_FILE_TYPES = "pdf,docx,doc,txt,jpg,png"
