
project_id = "kugocdtesaczbfrwblsi"

[functions.create-application]
verify_jwt = false

[functions.openai-assistant]
verify_jwt = false
timeout_seconds = 90

[functions.extract-pdf-text]
verify_jwt = false
timeout_seconds = 120
