project_id = "kugocdtesaczbfrwblsi"

[functions.create-application]
verify_jwt = false

[functions.openai-assistant]
verify_jwt = false
timeout_seconds = 120

[functions.extract-pdf-text]
verify_jwt = false
timeout_seconds = 180

# Environment variables for OpenAI
[env]
OPENAI_API_KEY = "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"
MAX_FILE_SIZE_MB = "10"
ALLOWED_FILE_TYPES = "pdf,docx,doc,txt,jpg,png"
