
project_id = "kugocdtesaczbfrwblsi"

[api]
enabled = true
port = 54321
schemas = ["public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[auth]
enable_signup = true
enabled = true

[storage]
enabled = true

[realtime]
enabled = true

[functions]
serve_local_storage = true
[functions.training-chat]
verify_jwt = false
