
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kugocdtesaczbfrwblsi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt1Z29jZHRlc2FjemJmcndibHNpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1NzA0MjUsImV4cCI6MjA2MjE0NjQyNX0.nHNWlTMfxuwAKYaiw145IFTAx3R3sbfWygviPVSH-Zc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true
    },
    global: {
      headers: {
        'x-application-name': 'hrm-app'
      }
    }
  }
);

// Force TypeScript to use proper table types
export type Tables = Database['public']['Tables'];

// Helper function to check if a bucket exists with improved error handling
export async function checkBucketExists(bucketName: string): Promise<boolean> {
  try {
    const { data: buckets, error } = await supabase.storage.listBuckets();
    
    if (error) {
      console.error('Error checking buckets:', error);
      return false;
    }
    
    const bucketExists = buckets?.some(bucket => bucket.id === bucketName) || false;
    console.log(`Bucket '${bucketName}' exists: ${bucketExists}`);
    return bucketExists;
  } catch (err) {
    console.error('Exception checking bucket existence:', err);
    return false;
  }
}

// Helper function to verify bucket access permissions with improved error handling
export async function verifyBucketAccess(bucketName: string): Promise<boolean> {
  try {
    // Try to list files as a simple permission check
    const { data, error } = await supabase.storage
      .from(bucketName)
      .list('', { limit: 1 });
      
    if (error) {
      console.error(`Access check for bucket '${bucketName}' failed:`, error);
      return false;
    }
    
    console.log(`Successfully verified access to bucket '${bucketName}'`);
    return true;
  } catch (err) {
    console.error('Exception during bucket access verification:', err);
    return false;
  }
}

// Helper function to ensure a bucket exists by creating it if needed
export async function ensureBucketExists(bucketName: string): Promise<boolean> {
  try {
    // First check if the bucket already exists
    const bucketExists = await checkBucketExists(bucketName);
    
    if (bucketExists) {
      console.log(`Bucket '${bucketName}' already exists.`);
      // Verify we can access it
      return await verifyBucketAccess(bucketName);
    }

    console.log(`Bucket '${bucketName}' doesn't exist or isn't accessible.`);
    
    // We need to create the bucket through Supabase SQL - cannot be done directly from client
    // Instead, we'll attempt to verify access in case the bucket exists but wasn't listed
    const hasAccess = await verifyBucketAccess(bucketName);
    
    if (hasAccess) {
      console.log(`Bucket '${bucketName}' is accessible even though it wasn't listed.`);
      return true;
    }
    
    console.log(`Cannot access bucket '${bucketName}'. It may need to be created via SQL.`);
    return false;
  } catch (err) {
    console.error('Error ensuring bucket exists:', err);
    return false;
  }
}
