// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rlswwkisxwcjixzdjmiv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJsc3d3a2lzeHdjaml4emRqbWl2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5NTMzNzcsImV4cCI6MjA2MTUyOTM3N30.OjUzXQZAONdhXGLZ9sGij5Co6PCjyx5PRBK9q_Hv3mg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);